name: flow_builder
description: Flows made easy in Flutter

version: 0.0.1-dev.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  flutter_bloc: ^6.0.0
